title: PCED Coding
description: Prompted Computational Essay Development Coding Resources and Tutorials
theme: jekyll-theme-slate

# Custom settings
show_downloads: false

# Build settings
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: /:title/

# Important: This ensures URLs don't require .html extension
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Collections
collections:
  lessons:
    output: true
    permalink: /:collection/:name/

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Custom variables
github:
  is_project_page: true
  repository_url: https://github.com/nickduran/PCED

# URL settings - add or modify these to match your setup
baseurl: "/PCED" # the subpath of your site - usually your repository name
url: "https://nickduran.github.io" # the base hostname & protocol for your site

# Assets
sass:
  style: compressed